### ISSUE TITLE
Add a feature for personal events

### ISSUE THREAD

**Issue by AuroMun** [OSDG-IIITH/CalenZone#6]
On import, there are no tags on events - Make them all personal.

**Comment by adarshsanjeev** [comment]
By default, they are. No tags means they only show up in "My Events"

**Comment by mukulhase** [comment]
@adarshsanjeev they won't show up in the calendar

**Comment by mukulhase** [comment]
Let's add a policy:
Owners of events can see their events even if they aren't a part of the group
